if (EXISTS "$ENV{PnDriver_ROOT}")
  set(PnDriver_FOUND TRUE)
  set(PnDriver_INCLUDE_DIR "$ENV{PnDriver_ROOT}/include")
  if (ADAPTIO_DEBUG_MODE STREQUAL "On" AND CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(PnDriver_LIBRARIES "pndriver_debug_x64")
  else ()
    set(PnDriver_LIBRARIES "pndriver_x64")
  endif()
  set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
  link_directories("$ENV{PnDriver_ROOT}/lib")
else ()
  set(PnDriver_FOUND FALSE)
endif ()
